### ISSUE TITLE
Java compiler error

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [Piasy/webrtc#1]
I use Android Studio 3.1. ndk version: android-ndk-r15c
And import new project `../webrtc/sdk/android_gradle/`, 
There exisit some Java compiler errors.
![image](https://user-images.githubusercontent.com/9837705/50883447-0dd53c00-1423-11e9-968e-350bf5b26674.png)
Hope you give me some advise. I just want to debug the webrtc native code with CMake in Android Studio. Thanks!

**Comment by Piasy** [comment]
Cool, I just published it yesterday and you are trying it :)

Actually I'm working on this now, I'll fix that tonight, stay tuned!

**Comment by Piasy** [comment]
Good news is I fixed all problems, C++ code debugging works well, only for arm64-v8a architecture.

But I'm going to move this project to https://github.com/Piasy/AppRTC-Android , so this issue will disappear.
